# Generated by Django 3.2.7 on 2021-10-05 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city_name', models.CharField(max_length=100)),
                ('difference_to_gmt', models.IntegerField(validators=[django.core.validators.MinValueValidator(-12), django.core.validators.MaxValueValidator(14)])),
            ],
        ),
    ]
