# Generated by Django 3.2.7 on 2021-10-09 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_timezone_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timezone',
            options={'permissions': (('is_admin_user', 'Admin User'),)},
        ),
        migrations.RemoveField(
            model_name='timezone',
            name='difference_to_gmt',
        ),
    ]
